"""recreate client table

Revision ID: 008db9234c45
Revises: 672cb877d586
Create Date: 2019-01-02 23:20:23.018388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008db9234c45'
down_revision = '672cb877d586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('surname', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_email'), 'client', ['email'], unique=True)
    op.create_index(op.f('ix_client_phone_number'), 'client', ['phone_number'], unique=True)
    op.create_index(op.f('ix_client_surname'), 'client', ['surname'], unique=False)
    op.create_foreign_key(None, 'opinion', 'client', ['client_id'], ['id'])
    op.create_foreign_key(None, 'order', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'opinion', type_='foreignkey')
    op.drop_index(op.f('ix_client_surname'), table_name='client')
    op.drop_index(op.f('ix_client_phone_number'), table_name='client')
    op.drop_index(op.f('ix_client_email'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
