"""add timestamp to reviews and clients reigstration date

Revision ID: 0e011be97361
Revises: b33c554c8cb2
Create Date: 2019-01-04 20:01:05.188732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e011be97361'
down_revision = 'b33c554c8cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('registered_on', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_client_registered_on'), 'client', ['registered_on'], unique=False)
    op.add_column('opinion', sa.Column('posted_on', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_opinion_posted_on'), 'opinion', ['posted_on'], unique=False)
    op.add_column('review', sa.Column('posted_on', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_review_posted_on'), 'review', ['posted_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_posted_on'), table_name='review')
    op.drop_column('review', 'posted_on')
    op.drop_index(op.f('ix_opinion_posted_on'), table_name='opinion')
    op.drop_column('opinion', 'posted_on')
    op.drop_index(op.f('ix_client_registered_on'), table_name='client')
    op.drop_column('client', 'registered_on')
    # ### end Alembic commands ###
