"""remove not null constaraints from client name and surname:


Revision ID: 18b9fbc5c1af
Revises: 210a545ec755
Create Date: 2018-12-31 11:05:23.919509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18b9fbc5c1af'
down_revision = '210a545ec755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('client', 'surname',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('order', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('order', 'payment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'payment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('client', 'surname',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('client', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
