"""add password hash & change phone_number to strign in client model

Revision ID: 210a545ec755
Revises: 7c17915af23b
Create Date: 2018-12-23 11:55:12.596756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210a545ec755'
down_revision = '7c17915af23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('password_hash', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'password_hash')
    # ### end Alembic commands ###
