"""add cost to delivery method model

Revision ID: 28c03e139752
Revises: dd58226e94eb
Create Date: 2019-01-11 18:49:36.840985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c03e139752'
down_revision = 'dd58226e94eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_method', sa.Column('cost', sa.Numeric(), nullable=False))
    op.create_index(op.f('ix_delivery_method_cost'), 'delivery_method', ['cost'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_method_cost'), table_name='delivery_method')
    op.drop_column('delivery_method', 'cost')
    # ### end Alembic commands ###
