"""remove isbn

Revision ID: 3b7eeb9526ad
Revises: ff252654b4c1
Create Date: 2019-01-02 21:04:10.605077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7eeb9526ad'
down_revision = 'ff252654b4c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_book_ISBN', table_name='book')
    op.drop_column('book', 'ISBN')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('ISBN', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_book_ISBN', 'book', ['ISBN'], unique=True)
    # ### end Alembic commands ###
