"""add isbn

Revision ID: 672cb877d586
Revises: 3b7eeb9526ad
Create Date: 2019-01-02 21:06:27.700986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672cb877d586'
down_revision = '3b7eeb9526ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('ISBN', sa.String(length=13), nullable=True))
    op.create_index(op.f('ix_book_ISBN'), 'book', ['ISBN'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_ISBN'), table_name='book')
    op.drop_column('book', 'ISBN')
    # ### end Alembic commands ###
