"""change loc

Revision ID: 7c17915af23b
Revises: c7abf0f37537
Create Date: 2018-12-13 21:34:52.105850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c17915af23b'
down_revision = 'c7abf0f37537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts_genres',
    sa.Column('category_discount_id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['category_discount_id'], ['category_discount.id'], ),
    sa.ForeignKeyConstraint(['genre_name'], ['genre.name'], ),
    sa.PrimaryKeyConstraint('category_discount_id', 'genre_name')
    )
    op.drop_table('discounts_genres_association')
    op.add_column('order', sa.Column('_location_fk', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_order__location_fk'), 'order', ['_location_fk'], unique=False)
    op.create_foreign_key(None, 'order', 'location', ['_location_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_index(op.f('ix_order__location_fk'), table_name='order')
    op.drop_column('order', '_location_fk')
    op.create_table('discounts_genres_association',
    sa.Column('category_discount_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_discount_id'], ['category_discount.id'], name='discounts_genres_association_category_discount_id_fkey'),
    sa.ForeignKeyConstraint(['genre_name'], ['genre.name'], name='discounts_genres_association_genre_name_fkey'),
    sa.PrimaryKeyConstraint('category_discount_id', 'genre_name', name='discounts_genres_association_pkey')
    )
    op.drop_table('discounts_genres')
    # ### end Alembic commands ###
