"""change category_discount percentage to unit

Revision ID: 7faa4c5c6b75
Revises: 080534ba8038
Create Date: 2019-01-16 18:54:15.829140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7faa4c5c6b75'
down_revision = '080534ba8038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_discount', sa.Column('discount_unit', sa.String(length=16), nullable=True))
    op.drop_column('category_discount', 'discount_percent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_discount', sa.Column('discount_percent', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('category_discount', 'discount_unit')
    # ### end Alembic commands ###
