"""add status column to order table

Revision ID: 9d16608457cd
Revises: 7faa4c5c6b75
Create Date: 2019-01-16 19:28:42.926675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d16608457cd'
down_revision = '7faa4c5c6b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_column('order', 'status')
    # ### end Alembic commands ###
