"""Recreate category_discount

Revision ID: a3882df7a116
Revises: c89c5e6fd7b1
Create Date: 2019-01-19 15:05:08.208122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3882df7a116'
down_revision = 'c89c5e6fd7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discounts_genres')
    op.add_column('category_discount', sa.Column('discount_unit', sa.String(length=16), nullable=True))
    op.drop_column('category_discount', 'discount_percent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_discount', sa.Column('discount_percent', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('category_discount', 'discount_unit')
    op.create_table('discounts_genres',
    sa.Column('category_discount_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genre_name'], ['genre.name'], name='discounts_genres_genre_name_fkey'),
    sa.PrimaryKeyConstraint('category_discount_id', 'genre_name', name='discounts_genres_pkey')
    )
    # ### end Alembic commands ###
