"""add status column to order table

Revision ID: ab62569e41f8
Revises: 9d16608457cd
Create Date: 2019-01-17 01:51:43.681342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab62569e41f8'
down_revision = '9d16608457cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('_location_fk', sa.Integer(), nullable=True),
    sa.Column('payment_method_name', sa.String(length=64), nullable=True),
    sa.Column('delivery_method_name', sa.String(length=64), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('delivered_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('total_price', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['_location_fk'], ['location.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['delivery_method_name'], ['delivery_method.name'], ),
    sa.ForeignKeyConstraint(['payment_method_name'], ['payment_method.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order__location_fk'), 'order', ['_location_fk'], unique=False)
    op.create_index(op.f('ix_order_client_id'), 'order', ['client_id'], unique=False)
    op.create_index(op.f('ix_order_delivered_on'), 'order', ['delivered_on'], unique=False)
    op.create_index(op.f('ix_order_delivery_method_name'), 'order', ['delivery_method_name'], unique=False)
    op.create_index(op.f('ix_order_order_date'), 'order', ['order_date'], unique=False)
    op.create_index(op.f('ix_order_payment_date'), 'order', ['payment_date'], unique=False)
    op.create_index(op.f('ix_order_payment_id'), 'order', ['payment_id'], unique=False)
    op.create_index(op.f('ix_order_payment_method_name'), 'order', ['payment_method_name'], unique=False)
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('body', sa.String(length=4096), nullable=False),
    sa.Column('mark', sa.Integer(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('downvotes', sa.Integer(), nullable=False),
    sa.Column('posted_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_posted_on'), 'review', ['posted_on'], unique=False)
    op.create_table('item_ordered',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'book_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_ordered')
    op.drop_index(op.f('ix_review_posted_on'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_index(op.f('ix_order_payment_method_name'), table_name='order')
    op.drop_index(op.f('ix_order_payment_id'), table_name='order')
    op.drop_index(op.f('ix_order_payment_date'), table_name='order')
    op.drop_index(op.f('ix_order_order_date'), table_name='order')
    op.drop_index(op.f('ix_order_delivery_method_name'), table_name='order')
    op.drop_index(op.f('ix_order_delivered_on'), table_name='order')
    op.drop_index(op.f('ix_order_client_id'), table_name='order')
    op.drop_index(op.f('ix_order__location_fk'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
