"""change lazy

Revision ID: c7abf0f37537
Revises: f9e56ed7c0bc
Create Date: 2018-12-13 21:25:22.774531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7abf0f37537'
down_revision = 'f9e56ed7c0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts_genres_association',
    sa.Column('category_discount_id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['category_discount_id'], ['category_discount.id'], ),
    sa.ForeignKeyConstraint(['genre_name'], ['genre.name'], ),
    sa.PrimaryKeyConstraint('category_discount_id', 'genre_name')
    )
    op.drop_table('discounts_genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts_genres',
    sa.Column('category_discount_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_discount_id'], ['category_discount.id'], name='discounts_genres_category_discount_id_fkey'),
    sa.ForeignKeyConstraint(['genre_name'], ['genre.name'], name='discounts_genres_genre_name_fkey'),
    sa.PrimaryKeyConstraint('category_discount_id', 'genre_name', name='discounts_genres_pkey')
    )
    op.drop_table('discounts_genres_association')
    # ### end Alembic commands ###
