"""Remove unnecessary association table. Add type of discount to product_pricing

Revision ID: c89c5e6fd7b1
Revises: ab62569e41f8
Create Date: 2019-01-19 14:44:01.919040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89c5e6fd7b1'
down_revision = 'ab62569e41f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('min_order_value', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('max_discount_amount', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_discount_valid_from'), 'category_discount', ['valid_from'], unique=False)
    op.create_index(op.f('ix_category_discount_valid_until'), 'category_discount', ['valid_until'], unique=False)
    op.add_column('category_discount', sa.Column('genre_name', sa.String(length=32), nullable=False))
    op.drop_index('ix_category_discount_valid_until', table_name='category_discount')
    op.create_foreign_key(None, 'category_discount', 'genre', ['genre_name'], ['name'])
    op.drop_column('category_discount', 'min_order_value')
    op.drop_column('category_discount', 'max_discount_amount')
    op.drop_column('category_discount', 'id')
    op.add_column('product_pricing', sa.Column('discount_value', sa.Numeric(precision=11, scale=2), nullable=False))
    op.drop_column('product_pricing', 'price')
    op.drop_column('product_pricing', 'min_order_value')
    op.drop_column('product_pricing', 'max_discount_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_pricing', sa.Column('max_discount_amount', sa.NUMERIC(precision=11, scale=2), autoincrement=False, nullable=True))
    op.add_column('product_pricing', sa.Column('min_order_value', sa.NUMERIC(precision=11, scale=2), autoincrement=False, nullable=False))
    op.add_column('product_pricing', sa.Column('price', sa.NUMERIC(precision=11, scale=2), autoincrement=False, nullable=False))
    op.drop_column('product_pricing', 'discount_value')
    op.add_column('category_discount', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('category_discount', sa.Column('max_discount_amount', sa.NUMERIC(precision=11, scale=2), autoincrement=False, nullable=True))
    op.add_column('category_discount', sa.Column('min_order_value', sa.NUMERIC(precision=11, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'category_discount', type_='foreignkey')
    op.create_index('ix_category_discount_valid_until', 'category_discount', ['valid_until'], unique=False)
    op.drop_column('category_discount', 'genre_name')
    op.create_table('discounts_genres',
    sa.Column('category_discount_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_discount_id'], ['category_discount.id'], name='discounts_genres_category_discount_id_fkey'),
    sa.ForeignKeyConstraint(['genre_name'], ['genre.name'], name='discounts_genres_genre_name_fkey'),
    sa.PrimaryKeyConstraint('category_discount_id', 'genre_name', name='discounts_genres_pkey')
    )
    # ### end Alembic commands ###
