"""make name & surname columns in Client model obligatory

Revision ID: dd58226e94eb
Revises: 0e011be97361
Create Date: 2019-01-11 18:39:47.576068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd58226e94eb'
down_revision = '0e011be97361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('client', 'surname',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'surname',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('client', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
