"""add isbn number to book

Revision ID: ff252654b4c1
Revises: 18b9fbc5c1af
Create Date: 2019-01-02 20:50:35.027551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff252654b4c1'
down_revision = '18b9fbc5c1af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('ISBN', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_book_ISBN'), 'book', ['ISBN'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_ISBN'), table_name='book')
    op.drop_column('book', 'ISBN')
    # ### end Alembic commands ###
